# Generated by Django 2.2.15 on 2020-08-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200817_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='gjhghgjgjg',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='hgfhgfhgf',
        ),
    ]
