# Generated by Django 2.2.15 on 2020-08-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200817_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='title',
        ),
        migrations.AddField(
            model_name='customtext',
            name='titlegjhgjhgjhg',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
