# Generated by Django 2.2.15 on 2020-08-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200817_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='titlegjhgjhgjhg',
            new_name='title',
        ),
    ]
